---
id: PubSub
name: PubSub
full: Publish/Subscribe library
description: Horde Publish/Subscribe package that can act as an inter-app messaging hub.
list: dev
type: library
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
